import { JetBrains_Mono } from "next/font/google";
import "./globals.css";


//====Shared Component
import Header from "@/components/Shared/Header";

const JetBrainsMono = JetBrains_Mono({ 
  subsets: ["latin"],
  weight:["100","200","300","400","500","600","700","800"],
  variable:"--font-jetBrainMono"

});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetBrainsMono.variable}>
        <Header></Header>
        {children}



      </body>
    </html>
  );
}
